#
#
#

PWD     := $(shell pwd)
BIN_DIR := $(SRC_DIR)/build-$(BOARD_VERSION).x-$(TARGET_CPU)

ifeq ($(BOARD_VERSION), 5)

target := hal5x.ko
obj-m := hal5x.o
hal_type=GW50

hal5x-y := module.o
hal5x-y += init.o \
     msec-sched.o \
     clk-common.o \
     timeslots.o \
     dsp-check.o \
     dsp-common.o \
     channel.o \
     codec.o \
     vcodec.o \
     vdspmixer.o \
     pcm.o \
     g711.o \
     cb.o \
     vdsp.o \
     vmux.o \
     hal-ctl.o \
     ../version/version.o
     
endif

ifeq ($(BOARD_VERSION), 6)

target := hal6x.ko
obj-m := hal6x.o
hal_type=GW60

hal6x-y := module.o
hal6x-y += init.o \
     msec-sched.o \
     clk-common.o \
     timeslots.o \
     dsp-check.o \
     dsp-common.o \
     channel.o \
     codec.o \
     vcodec.o \
     vdspmixer.o \
     pcm.o \
     g711.o \
     cb.o \
     vdsp.o \
     vmux.o \
     hal-ctl.o \
     ../version/version.o
     
endif

version_include := version.h
extra_cflags := -I$(SRC_DIR)/include -I$(SRC_DIR)/version -DHAL_$(hal_type) -DDEBUG \
 -DVERSION_INCLUDE=\"$(version_include)\" -DREVISION=${REVISION} -DBUILD_DATE="\"${BUILD_DATE}\"" -DCOPYRIGHT="\"${COPYRIGHT}\""

.PHONY: all clean

all:
	$(MAKE) EXTRA_CFLAGS='$(extra_cflags)' -C $(LINUX_DIR) M=$(PWD) modules

clean:
	$(MAKE) -C $(LINUX_DIR) M=$(PWD) clean

install:
	$(MAKE) EXTRA_CFLAGS='$(extra_cflags)' -C $(LINUX_DIR) M=$(PWD) INSTALL_MOD_PATH='$(DEST_DIR)/' modules_install
	find $(PWD) -name $(target) -exec cp {} $(BIN_DIR) \;
